const translations = {
  en: {
    title: "Set Up Your Company - EZTime",
    header_company_title: "Your Company",
    step_your_details: "Your Details",
    step_company_details: "Company Details",
    step_choose_product: "Choose Product",
    step_verification: "Verification",
    step_start: "Start!",
    page_title: "Set Your Company",
    card_company_details: "Company Details",
    label_company_name: "Company Name",
    label_company_id: "Company ID",
    label_time_zone: "Time Zone",
    label_logo: "Logo",
    hint_logo: "Not have to but its makes you spacial",
    button_upload: "Upload",
    card_admin_details: "Admin Details",
    label_user_name: "User Name",
    label_password: "Password",
    placeholder_company_name: "Best Business",
    placeholder_company_id: "39480184",
    placeholder_user_name: "You can use Company ID",
    placeholder_password: "What is your password?",
    button_next: "Next",
    title_choose_product: "Choose Your Product - EZTime",
    page_title_how_to_start: "How you want to start?",
    product_attendance: "Attendance",
    product_attendance_desc: "All your business is need -",
    product_shift_organize: "Shift Organize",
    product_shift_organize_desc: "Control you Employees -",
    try_for_free: "Try For Free",
    nativeName: "English",
    direction: "ltr",
    welcome_to: "Welcome To",
    subtitle_part1: "Attendance system that designed",
    subtitle_part2: "for you",
    trial_days: "30 Days trail",
    trial_free: "FOR FREE",
    label_fullname: "Full Name",
    label_phone: "Phone Number",
    label_email: "Business Email",
    placeholder_name: "What is your name?",
    placeholder_phone: "50 123 4567",
    placeholder_email: "James@BestBusiness.com",
    button_text: "Let's GO!",
    holidays_management: "Holidays Management",
    expances_management: "Expances Management",
    mobile_app: "Mobile App",
    title_verification: "Verify Your Email - EZTime",
    verify_title: "Verify your email",
    verify_subtitle: "Enter the code we've sent you to your inbox",
    verify_didnt_get: "Didn't get the code?",
    verify_resend: "Resend it",
    verify_or: " or ",
    verify_change_mail: "Change Mail",
    verify_error: "Something Wrong, please check the code again",
    resend_sending: "Sending...",
    resend_sent: "Sent! Check your inbox.",
    modal_change_email_title: "Change Email Address",
    label_new_email: "New Email Address",
    button_update_email: "Update Email",
    error_invalid_email: "Please enter a valid email address.",
    title_success: "Setup Complete! - EZTime",
    button_go_to_dashboard: "Go to Dashboard",
       success_title: "All Set!",
    success_subtitle: "Your company has been configured successfully.",
    success_redirect_notice: "You will be redirected in {seconds} seconds...",
    success_redirecting: "Redirecting...",
  },
  he: {
    title: "הגדרת חברה - EZTime",
    header_company_title: "החברה שלך",
    step_your_details: "הפרטים שלך",
    step_company_details: "פרטי חברה",
    step_choose_product: "בחירת מוצר",
    step_verification: "אימות",
    step_start: "התחלה!",
    page_title: "הגדר את החברה שלך",
    card_company_details: "פרטי חברה",
    label_company_name: "שם חברה",
    label_company_id: "מספר חברה",
    label_time_zone: "אזור זמן",
    label_logo: "לוגו",
    hint_logo: "לא חובה, אבל זה הופך את זה למיוחד",
    button_upload: "העלאה",
    card_admin_details: "פרטי מנהל מערכת",
    label_user_name: "שם משתמש",
    label_password: "סיסמה",
    placeholder_company_name: "חברה של אלופים",
    placeholder_company_id: "39480184",
    placeholder_user_name: "אפשר להשתמש במספר החברה",
    placeholder_password: "מה הסיסמה שלך?",
    button_next: "הבא",
    title_choose_product: "בחירת מוצר - EZTime",
    page_title_how_to_start: "איך תרצו להתחיל?",
    product_attendance: "נוכחות",
    product_attendance_desc: "כל מה שהעסק שלך צריך -",
    product_shift_organize: "סידור משמרות",
    product_shift_organize_desc: "שלוט בעובדים שלך -",
    try_for_free: "נסה בחינם",
    nativeName: "עברית",
    direction: "rtl",
    welcome_to: "ברוכים הבאים ל-",
    subtitle_part1: "מערכת נוכחות שתוכננה",
    subtitle_part2: "במיוחד בשבילך",
    trial_days: "30 יום ניסיון",
    trial_free: "בחינם",
    label_fullname: "שם מלא",
    label_phone: "מספר טלפון",
    label_email: "כתובת אימייל עסקית",
    placeholder_name: "מהו שמך?",
    placeholder_phone: "50-123-4567",
    placeholder_email: "israel@bestbusiness.co.il",
    button_text: "יאללה, נתחיל!",
    holidays_management: "ניהול חגים",
    expances_management: "ניהול הוצאות",
    mobile_app: "אפליקציה למובייל",
    selectAtLeastOne: "בחר לפחות מוצר אחד כדי להמשיך",
    title_verification: "אימות אימייל - EZTime",
    verify_title: "אמת את האימייל שלך",
    verify_subtitle: "הזן את הקוד ששלחנו אליך לתיבת הדואר",
    verify_didnt_get: "לא קיבלת את הקוד?",
    verify_resend: "שלח שוב",
    verify_or: " או ",
    verify_change_mail: "שנה כתובת מייל",
    verify_error: "משהו השתבש, אנא בדוק את הקוד שוב",
    resend_sending: "שולח...",
    resend_sent: "נשלח! בדוק את תיבת הדואר.",
    modal_change_email_title: "שנה כתובת אימייל",
    label_new_email: "כתובת אימייל חדשה",
    button_update_email: "עדכן אימייל",
    error_invalid_email: "אנא הזן כתובת אימייל תקינה.",
    title_success: "ההגדרה הושלמה! - EZTime",
    button_go_to_dashboard: "מעבר למערכת",
    success_title: "הכל מוכן!",
    success_subtitle: "החברה שלך הוגדרה בהצלחה.",
    success_redirect_notice: "מיד תועבר למערכת בעוד {seconds} שניות...",
    success_redirecting: "מעביר אותך למערכת...",
  },
};
